### ISSUE TITLE
Service temporarily unavailable

### ISSUE THREAD

**Issue by paulprok** [ibonly/laravel-accountkit#12]
I get this message in case `$otpLogin = AccountKit::accountKitData($request->code);`
> Server error: GET https://graph.accountkit.com/v1.2/access_token?grant_type=authorization_code&code=<authorization_code>&access_token=AA%7C%7C resulted in a 500 Internal Server Error response: {"error":{"message":"Service temporarily unavailable","type":"EMApiException","is_transient":true,"code":2,"fbtrace_id": (truncated...)

**Comment by ibonly** [comment]
Hi @paulprok, sorry for getting back to you late. That error seems the issue is from facebook because everything seems ok on my side. Are you still having the issue?

**Comment by paulprok** [comment]
Sorry, project was clsoed. So issue should be closed too
